### DEFAULT VALUES FOR ED2 ###
{ # position control PID gains
  posCtlPid/xKd: 0.0,
  posCtlPid/xKi: 0.0,
  posCtlPid/xKp: 1,
  posCtlPid/yKd: 0.0,
  posCtlPid/yKi: 0.0,
  posCtlPid/yKp: 1,
  posCtlPid/zKd: 0.7,
  posCtlPid/zKi: 0.05,
  posCtlPid/zKp: 0.6,

  # attitude PID gains
  pid_attitude/pitch_kd: 0.0,
  pid_attitude/pitch_ki: 1.5,
  pid_attitude/pitch_kp: 3.3,
  pid_attitude/roll_kd: 0.0,
  pid_attitude/roll_ki: 1.5,
  pid_attitude/roll_kp: 3.3,
  pid_attitude/yaw_kd: 0.35,
  pid_attitude/yaw_ki: 1.0,
  pid_attitude/yaw_kp: 6.0,

  # rate PID gains
  pid_rate/pitch_kd: 2.6,
  pid_rate/pitch_ki: 440.0,
  pid_rate/pitch_kp: 190.0,
  pid_rate/roll_kd: 2.6,
  pid_rate/roll_ki: 440.0,
  pid_rate/roll_kp: 190.0,
  pid_rate/yaw_kd: 0.0,
  pid_rate/yaw_ki: 16.7,
  pid_rate/yaw_kp: 120.0
}